import { readFile, writeFile } from 'node:fs/promises';
const schema = JSON.parse(await readFile(new URL('../../../docs/protocol/client-events.schema.json', import.meta.url)));
const lines = schema.oneOf.map(s => {
  const d = s.properties.data;
  const fields = Object.entries(d.properties).map(([k, v]) => `${k}${d.required?.includes(k) ? '' : '?'}: ${v.type === 'integer' ? 'number' : v.type}`).join('; ');
  return `  | { type: '${s.properties.type.const}'; data${s.required.includes('data') ? '' : '?'}: { ${fields} }${Array.isArray(d.type) ? ' | null' : ''} }`;
});
const output = '// Generated by scripts/wire-types.mjs from the v1 structural schema; state restrictions remain runtime rules.\nexport type ClientEvent = { event_id?: string; session_id?: string; generation_id?: string } & (\n' + lines.join('\n') + '\n);\n';
const file = new URL('../src/client-events.ts', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(file, 'utf8') !== output) throw Error('Client schema/type drift; run node scripts/wire-types.mjs');
} else await writeFile(file, output);
