// Generated by scripts/wire-types.mjs from the v1 structural schema; state restrictions remain runtime rules.
export type ClientEvent = { event_id?: string; session_id?: string; generation_id?: string } & (
  | { type: 'generation.cancel'; data?: {  } | null }
  | { type: 'generation.create'; data?: { output?: string; speed?: number; voice?: string } | null }
  | { type: 'input_audio.cancel'; data?: {  } | null }
  | { type: 'input_audio.commit'; data?: {  } | null }
  | { type: 'input_audio.speech_end'; data?: {  } | null }
  | { type: 'input_audio.speech_start'; data?: { interruption_id?: string } | null }
  | { type: 'input_audio.start'; data: { channels: number; encoding: string; mode?: string; sample_rate: number } }
  | { type: 'input_audio.stop'; data?: {  } | null }
  | { type: 'input_audio.vad_misfire'; data?: {  } | null }
  | { type: 'input_text.commit'; data: { output?: string; text: string } }
  | { type: 'interruption.failed'; data: { interruption_id: string } }
  | { type: 'interruption.suspected'; data: { interruption_id: string } }
  | { type: 'ping'; data?: {  } | null }
  | { type: 'playback.configure'; data: { flow_control: string } }
  | { type: 'playback.credit'; data: { buffered_source_frames: number; capacity_source_frames: number; played_source_frames: number; received_source_frames: number } }
  | { type: 'playback.overflow'; data?: { interruption_id?: string } | null }
  | { type: 'playback.paused'; data: { interruption_id: string; played_seconds?: number; played_source_frames?: number } }
  | { type: 'playback.progress'; data?: { played_seconds?: number; played_source_frames?: number } | null }
  | { type: 'response.text.delta'; data: { text: string } }
  | { type: 'response.text.done'; data?: {  } | null }
  | { type: 'session.close'; data?: {  } | null }
  | { type: 'session.configure'; data: { audio_flow_control?: string; protocol_version: string } }
);
