package audio

import (
	"sync"
	"time"
)

// PlaybackSnapshot is an immutable snapshot of the playback state
// for a single generation.
//
// All audio positions are represented as audio frames.
//
// One frame represents one point in time across all channels:
//
//	mono:   1 frame = 1 sample
//	stereo: 1 frame = 2 samples
//
// Using frames keeps playback timing independent of channel count.
type PlaybackSnapshot struct {
	GenerationID string

	SampleRate int
	Channels   int

	GeneratedFrames int64
	SentFrames      int64
	PlayedFrames    int64

	StartedAt time.Time
	UpdatedAt time.Time
}

// PlaybackTimeline tracks how far audio for one generation has
// progressed through the realtime audio pipeline.
//
// It separately tracks:
//
//	generated: audio produced by the TTS/audio runtime
//	sent:      audio successfully sent to the client
//	played:    audio actually consumed by the client playback runtime
//
// The timeline is safe for concurrent use.
type PlaybackTimeline struct {
	mu sync.RWMutex

	generationID string

	sampleRate int
	channels   int

	generatedFrames int64
	sentFrames      int64
	playedFrames    int64

	startedAt time.Time
	updatedAt time.Time
}

func NewPlaybackTimeline(
	generationID string,
) *PlaybackTimeline {
	now := time.Now().UTC()

	return &PlaybackTimeline{
		generationID: generationID,
		startedAt:    now,
		updatedAt:    now,
	}
}

// SetFormat records the audio format used by the timeline.
//
// SampleRate is expressed in frames per second.
// Channels describes how many samples exist in each frame.
func (t *PlaybackTimeline) SetFormat(
	sampleRate int,
	channels int,
) {
	t.mu.Lock()
	defer t.mu.Unlock()

	if sampleRate > 0 {
		t.sampleRate = sampleRate
	}

	if channels > 0 {
		t.channels = channels
	}

	t.updatedAt = time.Now().UTC()
}

// AddGenerated records frames successfully produced by the
// audio synthesis/runtime pipeline.
func (t *PlaybackTimeline) AddGenerated(
	frames int64,
) {
	if frames <= 0 {
		return
	}

	t.mu.Lock()
	defer t.mu.Unlock()

	t.generatedFrames += frames
	t.updatedAt = time.Now().UTC()
}

// AddSent records frames successfully sent to the client.
func (t *PlaybackTimeline) AddSent(
	frames int64,
) {
	if frames <= 0 {
		return
	}

	t.mu.Lock()
	defer t.mu.Unlock()

	t.sentFrames += frames
	t.updatedAt = time.Now().UTC()
}

// SetPlayed records the absolute playback position reported by
// the client.
//
// Playback progress is monotonic. An older or delayed progress
// report must never move the timeline backwards.
//
// PlayedFrames is also clamped to SentFrames when sent progress
// is known, because the client cannot legitimately play audio
// that has not been sent.
func (t *PlaybackTimeline) SetPlayed(
	frames int64,
) {
	if frames < 0 {
		return
	}

	t.mu.Lock()
	defer t.mu.Unlock()

	if t.sentFrames > 0 &&
		frames > t.sentFrames {
		frames = t.sentFrames
	}

	if frames <= t.playedFrames {
		return
	}

	t.playedFrames = frames
	t.updatedAt = time.Now().UTC()
}

// Snapshot returns a consistent immutable view of the timeline.
func (t *PlaybackTimeline) Snapshot() PlaybackSnapshot {
	t.mu.RLock()
	defer t.mu.RUnlock()

	return PlaybackSnapshot{
		GenerationID: t.generationID,

		SampleRate: t.sampleRate,
		Channels:   t.channels,

		GeneratedFrames: t.generatedFrames,
		SentFrames:      t.sentFrames,
		PlayedFrames:    t.playedFrames,

		StartedAt: t.startedAt,
		UpdatedAt: t.updatedAt,
	}
}

func (s PlaybackSnapshot) GeneratedDuration() time.Duration {
	return framesToDuration(
		s.GeneratedFrames,
		s.SampleRate,
	)
}

func (s PlaybackSnapshot) SentDuration() time.Duration {
	return framesToDuration(
		s.SentFrames,
		s.SampleRate,
	)
}

func (s PlaybackSnapshot) PlayedDuration() time.Duration {
	return framesToDuration(
		s.PlayedFrames,
		s.SampleRate,
	)
}

// BufferedFrames returns the amount of audio that has been sent
// to the client but has not yet been reported as played.
func (s PlaybackSnapshot) BufferedFrames() int64 {
	buffered :=
		s.SentFrames -
			s.PlayedFrames

	if buffered < 0 {
		return 0
	}

	return buffered
}

func (s PlaybackSnapshot) BufferedDuration() time.Duration {
	return framesToDuration(
		s.BufferedFrames(),
		s.SampleRate,
	)
}

// UnsentFrames returns audio generated by the server but not yet
// successfully sent to the client.
func (s PlaybackSnapshot) UnsentFrames() int64 {
	unsent :=
		s.GeneratedFrames -
			s.SentFrames

	if unsent < 0 {
		return 0
	}

	return unsent
}

func (s PlaybackSnapshot) UnsentDuration() time.Duration {
	return framesToDuration(
		s.UnsentFrames(),
		s.SampleRate,
	)
}

func framesToDuration(
	frames int64,
	sampleRate int,
) time.Duration {
	if frames <= 0 || sampleRate <= 0 {
		return 0
	}

	seconds :=
		float64(frames) /
			float64(sampleRate)

	return time.Duration(
		seconds *
			float64(time.Second),
	)
}
